-- Noon Directory Tables (nd_ prefix)
-- This creates all tables for the directory platform without affecting existing tables

CREATE TABLE IF NOT EXISTS `nd_admins` (
  `id` VARCHAR(191) NOT NULL,
  `username` VARCHAR(191) NOT NULL,
  `hash` VARCHAR(191) NOT NULL,
  `hashedRt` VARCHAR(191) NULL,
  `photo` VARCHAR(191) NULL,
  `roles` VARCHAR(191) NOT NULL DEFAULT '[]',
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `RoleType` ENUM('SuperAdmin', 'Admin', 'Vendor') NOT NULL DEFAULT 'SuperAdmin',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nd_admins_username_key`(`username`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_admin_device_tokens` (
  `id` VARCHAR(191) NOT NULL,
  `client_token` VARCHAR(191) NOT NULL,
  `adminId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nd_admin_device_tokens_client_token_key`(`client_token`),
  FOREIGN KEY (`adminId`) REFERENCES `nd_admins`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_clients` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `apiKey` VARCHAR(191) NOT NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nd_clients_apiKey_key`(`apiKey`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_vendors` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NULL,
  `hash` VARCHAR(191) NOT NULL,
  `hashedRt` VARCHAR(191) NULL,
  `photo` VARCHAR(191) NULL,
  `province` VARCHAR(191) NULL,
  `address` TEXT NULL,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `isVerified` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'FALSE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nd_vendors_phone_key`(`phone`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_stores` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `logo` VARCHAR(191) NULL,
  `cover` VARCHAR(191) NULL,
  `phone` VARCHAR(191) NULL,
  `phone2` VARCHAR(191) NULL,
  `province` VARCHAR(191) NOT NULL,
  `address` TEXT NULL,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `vendorId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nd_stores_vendorId_key`(`vendorId`),
  FOREIGN KEY (`vendorId`) REFERENCES `nd_vendors`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_products` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `price` DOUBLE NULL,
  `image` VARCHAR(191) NULL,
  `category` VARCHAR(191) NULL,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `vendorId` VARCHAR(191) NOT NULL,
  `storeId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`vendorId`) REFERENCES `nd_vendors`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`storeId`) REFERENCES `nd_stores`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_directory_listings` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `category` ENUM('INSTITUTE', 'PHYSICAL_ACTIVITY', 'KINDERGARTEN', 'PRIVATE_SCHOOL', 'TEACHER', 'STATIONERY', 'LIBRARY', 'UNIFORM', 'SMART_TOYS', 'HEALTH_DENTAL', 'HEALTH_PEDIATRIC', 'HEALTH_SPECIALIST') NOT NULL,
  `province` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(191) NULL,
  `phone2` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `address` TEXT NULL,
  `description` TEXT NULL,
  `logo` VARCHAR(191) NULL,
  `website` VARCHAR(191) NULL,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `isFeatured` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'FALSE',
  `rating` DOUBLE NOT NULL DEFAULT 5.0,
  `viewCount` INT NOT NULL DEFAULT 0,
  `clickCount` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_directory_listing_images` (
  `id` VARCHAR(191) NOT NULL,
  `url` VARCHAR(191) NOT NULL,
  `directoryListingId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`directoryListingId`) REFERENCES `nd_directory_listings`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_reviews` (
  `id` VARCHAR(191) NOT NULL,
  `reviewerName` VARCHAR(191) NOT NULL,
  `reviewerPhone` VARCHAR(191) NULL,
  `rating` DOUBLE NOT NULL,
  `comment` TEXT NULL,
  `isApproved` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'FALSE',
  `directoryListingId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`directoryListingId`) REFERENCES `nd_directory_listings`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_job_seekers` (
  `id` VARCHAR(191) NOT NULL,
  `fullName` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NULL,
  `speciality` VARCHAR(191) NOT NULL,
  `province` VARCHAR(191) NOT NULL,
  `experience` TEXT NULL,
  `bio` TEXT NULL,
  `photo` VARCHAR(191) NULL,
  `cv` VARCHAR(191) NULL,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `isApproved` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_ad_requests` (
  `id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(191) NOT NULL,
  `category` ENUM('INSTITUTE', 'PHYSICAL_ACTIVITY', 'KINDERGARTEN', 'PRIVATE_SCHOOL', 'TEACHER', 'STATIONERY', 'LIBRARY', 'UNIFORM', 'SMART_TOYS', 'HEALTH_DENTAL', 'HEALTH_PEDIATRIC', 'HEALTH_SPECIALIST') NOT NULL,
  `province` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `logo` VARCHAR(191) NULL,
  `address` TEXT NULL,
  `email` VARCHAR(191) NULL,
  `website` VARCHAR(191) NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `adminNote` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_ad_request_images` (
  `id` VARCHAR(191) NOT NULL,
  `url` VARCHAR(191) NOT NULL,
  `adRequestId` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`adRequestId`) REFERENCES `nd_ad_requests`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_banners` (
  `id` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NULL,
  `description` VARCHAR(191) NULL,
  `url` VARCHAR(191) NOT NULL,
  `link` VARCHAR(191) NULL,
  `priority` INT NOT NULL DEFAULT 99999,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_settings` (
  `id` VARCHAR(191) NOT NULL,
  `key` VARCHAR(191) NOT NULL,
  `value` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nd_settings_key_key`(`key`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nd_disclaimers` (
  `id` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `isActive` ENUM('TRUE', 'FALSE') NOT NULL DEFAULT 'TRUE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
